services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./webroot:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./webroot/public:/var/www/html/public
      - ./webroot/App:/var/www/html/App

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db